apiVersion: v1
kind: ConfigMap
metadata:
  name: costcenter-config
data:
  app.properties: |2+
    camel.main.autowired-enabled=false

    quarkus.qpid-jms.url=amqp://messaging-b90e01e.openshift-operators.svc:5672
    quarkus.qpid-jms.username=user
    quarkus.qpid-jms.password=enmasse
    camel.component.kafka.brokers=stream-cluster-kafka-bootstrap.event-stream-project.svc:9092
