apiVersion: v1
kind: Secret
metadata: 
  name: connect-secret
type: Opaque
data: 
  identities.yaml: |-
    Y3JlZGVudGlhbHM6Ci0gdXNlcm5hbWU6IGRldmVsb3BlcgogIHBhc3N3b3JkOiBwYXNzd29yZAotIHVzZXJuYW1lOiBvcGVyYXRvcgogIHBhc3N3b3JkOiBwYXNzd29yZA==
